In [ ]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
words = open('names (2).txt','r').read().splitlines()

In [ ]:
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [ ]:
len(words)

32033

In [ ]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [ ]:
stoi

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [ ]:
block_size = 3 # length of context: no. of characters we use to predict the next

X, Y = [], []
for w in words[:5]:
    print(w)
    context = [0] * block_size

    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print(''.join(itos[i] for i in context), '-->', itos[ix])
        context = context[1:] + [ix] # crop and append, like a rolling window

X = torch.tensor(X)
Y = torch.tensor(Y)

emma
... --> e
..e --> m
.em --> m
emm --> a
mma --> .
olivia
... --> o
..o --> l
.ol --> i
oli --> v
liv --> i
ivi --> a
via --> .
ava
... --> a
..a --> v
.av --> a
ava --> .
isabella
... --> i
..i --> s
.is --> a
isa --> b
sab --> e
abe --> l
bel --> l
ell --> a
lla --> .
sophia
... --> s
..s --> o
.so --> p
sop --> h
oph --> i
phi --> a
hia --> .


In [ ]:
X.shape, X.dtype, Y.shape, Y.dtype

(torch.Size([32, 3]), torch.int64, torch.Size([32]), torch.int64)

In [ ]:
c = torch.randn(27,2)

In [ ]:
c

tensor([[ 1.2711e+00,  2.0840e+00],
        [ 3.5185e-01, -7.4009e-01],
        [ 2.1188e+00,  3.3328e-01],
        [ 9.9708e-02, -1.6931e+00],
        [-4.0406e-01, -1.6784e+00],
        [ 1.2742e+00, -1.3501e+00],
        [-2.3742e-01, -7.8502e-01],
        [-4.3150e-01,  1.0588e+00],
        [ 1.5313e+00, -6.2923e-01],
        [ 4.2047e-01,  6.8086e-01],
        [ 1.8013e+00,  1.8824e+00],
        [-2.0803e-01, -7.6876e-01],
        [ 6.0994e-01,  1.2312e+00],
        [-2.3668e-03, -4.0718e-01],
        [ 9.7354e-02,  5.1926e-01],
        [-1.0136e-01,  1.8421e+00],
        [-1.1138e+00,  1.1661e+00],
        [-9.0110e-01, -4.0414e-02],
        [-2.0012e+00,  2.9684e-01],
        [-2.4486e-02, -3.6078e-01],
        [-7.0885e-02,  2.1251e-01],
        [ 1.9446e+00,  4.0494e-02],
        [-6.6320e-02,  3.5024e-01],
        [-3.6145e-01,  3.9079e-01],
        [ 2.6205e+00,  2.3098e-02],
        [ 1.3774e+00,  1.2641e+00],
        [ 2.9975e-01, -1.7211e-02]])

In [ ]:
c[5]

tensor([ 1.2742, -1.3501])

In [ ]:
F.one_hot(torch.tensor(5),num_classes=27).dtype

torch.int64

In [ ]:
F.one_hot(torch.tensor(5),num_classes=27).float() @ c

tensor([ 1.2742, -1.3501])

In [ ]:
c[torch.tensor([5,6,7])]

tensor([[ 1.2742, -1.3501],
        [-0.2374, -0.7850],
        [-0.4315,  1.0588]])

In [ ]:
emb = c[X]
emb.shape

torch.Size([32, 3, 2])

In [ ]:
w1 = torch.randn(6,100)
b1 = torch.randn(100)

In [ ]:
emb

tensor([[[ 1.2711,  2.0840],
         [ 1.2711,  2.0840],
         [ 1.2711,  2.0840]],

        [[ 1.2711,  2.0840],
         [ 1.2711,  2.0840],
         [ 1.2742, -1.3501]],

        [[ 1.2711,  2.0840],
         [ 1.2742, -1.3501],
         [-0.0024, -0.4072]],

        [[ 1.2742, -1.3501],
         [-0.0024, -0.4072],
         [-0.0024, -0.4072]],

        [[-0.0024, -0.4072],
         [-0.0024, -0.4072],
         [ 0.3519, -0.7401]],

        [[ 1.2711,  2.0840],
         [ 1.2711,  2.0840],
         [ 1.2711,  2.0840]],

        [[ 1.2711,  2.0840],
         [ 1.2711,  2.0840],
         [-0.1014,  1.8421]],

        [[ 1.2711,  2.0840],
         [-0.1014,  1.8421],
         [ 0.6099,  1.2312]],

        [[-0.1014,  1.8421],
         [ 0.6099,  1.2312],
         [ 0.4205,  0.6809]],

        [[ 0.6099,  1.2312],
         [ 0.4205,  0.6809],
         [-0.0663,  0.3502]],

        [[ 0.4205,  0.6809],
         [-0.0663,  0.3502],
         [ 0.4205,  0.6809]],

        [[-0.0663,  0

In [ ]:
emb = emb.view(32,3,2)

In [ ]:
emb

tensor([[[ 1.2711,  2.0840],
         [ 1.2711,  2.0840],
         [ 1.2711,  2.0840]],

        [[ 1.2711,  2.0840],
         [ 1.2711,  2.0840],
         [ 1.2742, -1.3501]],

        [[ 1.2711,  2.0840],
         [ 1.2742, -1.3501],
         [-0.0024, -0.4072]],

        [[ 1.2742, -1.3501],
         [-0.0024, -0.4072],
         [-0.0024, -0.4072]],

        [[-0.0024, -0.4072],
         [-0.0024, -0.4072],
         [ 0.3519, -0.7401]],

        [[ 1.2711,  2.0840],
         [ 1.2711,  2.0840],
         [ 1.2711,  2.0840]],

        [[ 1.2711,  2.0840],
         [ 1.2711,  2.0840],
         [-0.1014,  1.8421]],

        [[ 1.2711,  2.0840],
         [-0.1014,  1.8421],
         [ 0.6099,  1.2312]],

        [[-0.1014,  1.8421],
         [ 0.6099,  1.2312],
         [ 0.4205,  0.6809]],

        [[ 0.6099,  1.2312],
         [ 0.4205,  0.6809],
         [-0.0663,  0.3502]],

        [[ 0.4205,  0.6809],
         [-0.0663,  0.3502],
         [ 0.4205,  0.6809]],

        [[-0.0663,  0

In [ ]:
emb = emb.view(32,6)

In [ ]:
emb.shape

torch.Size([32, 6])

In [ ]:
h = emb.view(emb.shape[0],6) @ w1 + b1

In [ ]:
h.shape

torch.Size([32, 100])

In [ ]:
w2 = torch.randn(100,27)
b2 = torch.randn(27)

In [ ]:
logits = h @ w2 + b2

In [ ]:
logits.shape

torch.Size([32, 27])

In [ ]:
counts = logits.exp()

In [ ]:
prob = counts / counts.sum(1,keepdims=True)

In [ ]:
prob

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,        nan, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.2285e-24, 1.9755e-29, 3.4707e-30, 9.5227e-33, 0.0000e+00, 2.5041e-42,
         1.1843e-30, 0.0000e+00, 1.4013e-45, 4.8973e-26, 1.0000e+00, 1.2423e-34,
         0.0000e+00, 0.0000e+00, 3.1885e-35, 4.5493e-29, 8.7344e-19, 5.6065e-18,
         1.3559e-32, 1.8860e-13, 8.9782e-22, 0.0000e+00, 2.6361e-30, 5.4726e-08,
         2.2384e-41, 1.0201e-32, 1.4778e-18],
        [6.8239e-24, 2.0200e-25, 2.0319e-17, 2.8026e-45, 2.5529e-38, 1.5946e-24,
         2.8061e-26, 1.9831e-35, 0.0000e+00, 1.5604e-05, 1.1777e-16, 6.8729e-34,
         6.1493e-33, 1.4348e-29, 3.9296e-34, 1.0932e-25, 1.3889e-08, 9.9998e-01,
         2.3622e-

In [ ]:
counts / counts.sum(1,keepdims=True)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,        nan, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.2285e-24, 1.9755e-29, 3.4707e-30, 9.5227e-33, 0.0000e+00, 2.5041e-42,
         1.1843e-30, 0.0000e+00, 1.4013e-45, 4.8973e-26, 1.0000e+00, 1.2423e-34,
         0.0000e+00, 0.0000e+00, 3.1885e-35, 4.5493e-29, 8.7344e-19, 5.6065e-18,
         1.3559e-32, 1.8860e-13, 8.9782e-22, 0.0000e+00, 2.6361e-30, 5.4726e-08,
         2.2384e-41, 1.0201e-32, 1.4778e-18],
        [6.8239e-24, 2.0200e-25, 2.0319e-17, 2.8026e-45, 2.5529e-38, 1.5946e-24,
         2.8061e-26, 1.9831e-35, 0.0000e+00, 1.5604e-05, 1.1777e-16, 6.8729e-34,
         6.1493e-33, 1.4348e-29, 3.9296e-34, 1.0932e-25, 1.3889e-08, 9.9998e-01,
         2.3622e-

In [ ]:
counts / counts.sum(1,keepdims=True)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,        nan, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.2285e-24, 1.9755e-29, 3.4707e-30, 9.5227e-33, 0.0000e+00, 2.5041e-42,
         1.1843e-30, 0.0000e+00, 1.4013e-45, 4.8973e-26, 1.0000e+00, 1.2423e-34,
         0.0000e+00, 0.0000e+00, 3.1885e-35, 4.5493e-29, 8.7344e-19, 5.6065e-18,
         1.3559e-32, 1.8860e-13, 8.9782e-22, 0.0000e+00, 2.6361e-30, 5.4726e-08,
         2.2384e-41, 1.0201e-32, 1.4778e-18],
        [6.8239e-24, 2.0200e-25, 2.0319e-17, 2.8026e-45, 2.5529e-38, 1.5946e-24,
         2.8061e-26, 1.9831e-35, 0.0000e+00, 1.5604e-05, 1.1777e-16, 6.8729e-34,
         6.1493e-33, 1.4348e-29, 3.9296e-34, 1.0932e-25, 1.3889e-08, 9.9998e-01,
         2.3622e-

In [ ]:
loss = -prob[torch.arange(32),Y].log().mean()

In [ ]:
loss

tensor(inf)

In [ ]:
Y

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
         1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0])